apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: dev
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "devops_app"
  POSTGRES_USER: "postgres"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "development"