apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
  namespace: dev
type: Opaque
data:
  # Base64 encoded values
  # postgres_password = "password" -> cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=